name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@4

      - name: Run Script
        run: |
          npm i --force
          npm run build

      - name: Setup Python
        uses: actions/setup-python@5

      - name: Deploy
        run: |
          python -m pip install -r requirements.txt
          python script.py
          
